
INSERT INTO PROFESSIONS (NAME, NOTE) VALUES ('Бухгалтер', 'note');
INSERT INTO PROFESSIONS (NAME, NOTE) VALUES ('Программист', 'note');
INSERT INTO PROFESSIONS (NAME, NOTE) VALUES ('Директор', 'note');
INSERT INTO PROFESSIONS (NAME, NOTE) VALUES ('Менеджер', 'note');

INSERT INTO DEPARTMENTS (NAME, PARENT_ID, NOTE) VALUES ('Бухгалтерский отдел', NULL, 'note');
INSERT INTO DEPARTMENTS (NAME, PARENT_ID, NOTE) VALUES ('Расчётная группа', 1, 'note');
INSERT INTO DEPARTMENTS (NAME, PARENT_ID, NOTE) VALUES ('Программный отдел', NULL, 'note');
INSERT INTO DEPARTMENTS (NAME, PARENT_ID, NOTE) VALUES ('Управление', NULL, 'note');
INSERT INTO DEPARTMENTS (NAME, PARENT_ID, NOTE) VALUES ('Отдел продаж', NULL, 'note');

INSERT INTO EMPLOYEES (FIO, PROFESSION_ID, DEPARTMENT_ID, NOTE) VALUES ('Малинова Алла Борисовна ', 1, 1, 'note');
INSERT INTO EMPLOYEES (FIO, PROFESSION_ID, DEPARTMENT_ID, NOTE) VALUES ('Климов Андрей Андреевич', 1, 2, 'note');
INSERT INTO EMPLOYEES (FIO, PROFESSION_ID, DEPARTMENT_ID, NOTE) VALUES ('Голубев Дмитрий Александрович', 2, 3, 'note');
INSERT INTO EMPLOYEES (FIO, PROFESSION_ID, DEPARTMENT_ID, NOTE) VALUES ('Шпак Василий Иванович', 3, 4, 'note');
